---
- hosts: default
  become: true
  tasks:
   # GENERIC
   - name: Setup sudoers
     copy:
       src: files/01_intelmq_tutorial
       dest: /etc/sudoers.d/01_intelmq_tutorial
       owner: root
       group: root
       mode: 0440
       validate: /usr/sbin/visudo -cf %s
   - name: provide MOTD
     copy:
       src: motd
       dest: /etc/
   - name: Set roundcube dbconfig options
     debconf:
       name: roundcube-core
       question: roundcube/database-type
       value: sqlite3
       vtype: string
   - name: Add apt key
     apt_key:
       url: https://download.opensuse.org/repositories/home:sebix:intelmq/Debian_10/Release.key
       state: present
   - name: Setup APT repository Debian 10
     apt_repository:
       repo: deb http://download.opensuse.org/repositories/home:/sebix:/intelmq/Debian_10/ /
       state: present
   - name: install packages
     package:
       name:
       - vim
       - screen
       - git
       # intelmq
       - redis
       - jq
       - python3-pip
       - python3-requests
       - python3-redis
       - python3-dnspython
       - python3-psutil
       - python3-dateutil
       - python3-termstyle
       - python3-tz
       - python3-yaml
       - python3-cerberus
       # intelmq optional
       - python3-geoip2
       - postgresql
       - python3-psycopg2
       - python3-bs4
       - rabbitmq-server
       - python3-pika
       - python3-imbox
       # for the postgresql_* ansible modules
       - python-psycopg2
       # for ansible unarchive
       - unzip
       # for webinput
       - python-pkg-resources
       - libapache2-mod-php7.3
       - libapache2-mod-wsgi-py3
       # for tutorial
       - pandoc
       # mailserver
       - postfix-pcre
       - dovecot-imapd
       - php-curl
       - php-xml
       - roundcube-sqlite3
       - roundcube-core
       - intelmq
       - intelmq-api
       - intelmq-manager
   # INTELMQ CORE
   - name: Create directories
     file:
       path: "{{ item }}"
       state: directory
       mode: 0755
       owner: intelmq
       group: intelmq
     with_items:
       - /var/lib/bots/asn_lookup/
       - /var/lib/bots/file-output/
       - /var/lib/bots/maxmind_geoip/
       - /var/lib/bots/modify/
       - /opt/dev_intelmq/
   - name: provide default crontab
     copy:
       src: default_crontab
       dest: /tmp/
   - name: install default crontab
     command: crontab -u intelmq /tmp/default_crontab
     become: True
   - name: Clone IntelMQ repository (needed for test data)
     git:
       repo: https://github.com/certtools/intelmq.git
       dest: /opt/dev_intelmq
       version: maintenance
     become_user: intelmq
     vars:
       # required because of become_user with an unprivileged user. see https://docs.ansible.com/ansible/latest/user_guide/become.html#id6
       ansible_ssh_pipelining: yes
   # INTELMQ OPTIONAL DEPENDENCIES
   - name: Install pyasn
     pip:
       name: pyasn
       executable: pip3
     become: True
   - name: Provide local lookup database for IP address to ASN
     shell: pyasn_util_download.py --latestv46 && pyasn_util_convert.py --single rib.* /var/lib/bots/asn_lookup/ipasn.dat
     args:
       chdir: /tmp/
       creates:
         /var/lib/bots/asn_lookup/ipasn.dat
     become_user: intelmq
     vars:
       # required because of become_user with an unprivileged user. see https://docs.ansible.com/ansible/latest/user_guide/become.html#id6
       ansible_ssh_pipelining: yes
   - name: Fetch download_mapping.py script
     get_url:
       url: https://raw.githubusercontent.com/certtools/intelmq/develop/contrib/malware_name_mapping/download_mapping.py
       dest: /usr/local/bin/download_mapping.py
       mode: '755'
   - name: Download Malware Name Mapping
     command:
       argv:
       - /usr/local/bin/download_mapping.py
       - --include-misp
       - /var/lib/bots/modify/malware_name_mapping.json
     args:
       creates: /var/lib/bots/modify/malware_name_mapping.json
   # INTELMQ-API
   - name: Install intelmq-api config
     copy:
       src: api-config.json
       dest: /etc/intelmq/api-config.json
       mode: '0664'
   # WEBINPUT
   - name: install intelmq-webinput-csv dependencies
     pip:
       name: hug
       executable: pip3
   - name: install intelmq-webinput-csv from pip
     pip:
       name: intelmq_webinput_csv >= 0.2.0
       executable: pip3
   - name: Enable Apache modules
     apache2_module:
       name: "{{item}}"
     with_items:
       - wsgi
       - proxy
       - proxy_http
       - rewrite
   - name: Write Apache configuration
     copy:
       src: apache.conf
       dest: /etc/apache2/sites-available/000-default.conf
   - name: Provide Webinput configuration
     copy:
       src: webinput_csv.conf
       dest: /etc/webinput_csv.conf
   - name: Restart Apache
     systemd:
       name: apache2
       state: restarted
   # POSTGRESQL
   - name: Create PostgreSQL HBA configuration
     copy:
       src: pg_hba.conf
       dest: /etc/postgresql/11/main/pg_hba.conf
   - name: Restart Apache
     systemd:
       name: postgresql
       state: restarted
   - name: Create PostgreSQL User
     postgresql_user:
       name: intelmq
       password: intelmq
       role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
     become_user: postgres
     vars:
       # required because of become_user with an unprivileged user. see https://docs.ansible.com/ansible/latest/user_guide/become.html#id6
       ansible_ssh_pipelining: yes
   - name: Create PostgreSQL Database
     postgresql_db:
       name: intelmq
       owner: intelmq
     become_user: postgres
     vars:
       # required because of become_user with an unprivileged user. see https://docs.ansible.com/ansible/latest/user_guide/become.html#id6
       ansible_ssh_pipelining: yes
   - name: Transfer SQL file
     copy:
       src: initdb.sql
       dest: /var/lib/bots/sql/
   - name: Create events table
     postgresql_query:
       db: intelmq
       path_to_script: /var/lib/bots/sql/initdb.sql
       login_user: intelmq
       login_password: intelmq
   # SQLITE
   - name: Move TI to SQLite converter
     copy:
       src: ti-to-sqlite-cc.py
       dest: /usr/local/bin/
       mode: '0755'
   - name: Move TI JSON database
     copy:
       src: ti-teams.json
       dest: /var/lib/bots/sql/
   - name: Execute TI to SQLite converter
     command: /usr/local/bin/ti-to-sqlite-cc.py --ti /var/lib/bots/sql/ti-teams.json /var/lib/bots/sql/ti-teams.sqlite
     args:
       creates: /var/lib/bots/sql/ti-teams.sqlite
   # FODY
   - name: install intelmq-fody-backend via pip from cert.at repository fork
     pip:
       name: git+http://github.com/certat/intelmq-fody-backend.git@staging#egg=intelmq_fody_backend
       executable: pip3
   - name: install intelmq-fody from pre-compiled archive (cert.at repository fork)
     unarchive:
       src: https://github.com/certat/intelmq-fody/releases/download/2020-01-21/intelmq-fody.tar.gz
       dest: /var/www/html/
       remote_src: yes
     become: True
   - name: Install Fody events api configuration
     copy:
       src: eventdb-serve.conf
       dest: /etc/intelmq/
   # LANDING PAGE
   - name: install landing page
     copy:
       src: landingpage.html
       dest: /var/www/html/index.html
   # RabbitMQ
   - name: Start RabbitMQ for configuration
     systemd:
       name: rabbitmq-server
       state: started
   - name: Enable RabbitMQ plugins
     copy:
       src: enabled_plugins
       dest: /etc/rabbitmq/
   - name: create RabbitMQ admin user
     shell: rabbitmqctl list_users | egrep ^admin || sudo rabbitmqctl add_user admin admin
   - name: make RabbitMQ admin user an administrator
     command: rabbitmqctl set_user_tags admin administrator management
   - name: create RabbitMQ intelmq user
     shell: rabbitmqctl list_users | egrep ^intelmq || sudo rabbitmqctl add_user intelmq intelmq
   - name: configure RabbitMQ intelmq user
     command: rabbitmqctl set_user_tags intelmq montoring
   - name: allow intelmq user access to vhost /
     command: rabbitmqctl set_permissions intelmq ".*" ".*" ".*"
   - name: allow admin user access to vhost /
     command: rabbitmqctl set_permissions admin ".*" ".*" ".*"
   - name: Stop and disable RabbitMQ
     systemd:
       name: rabbitmq-server
       state: stopped
       enabled: no
   # TUTORIAL
   - name: Clone tutorial repository
     git:
       repo: https://github.com/certtools/intelmq-tutorial.git
       dest: /home/user/intelmq-tutorial/
       version: master
     become_user: user
     vars:
       # required because of become_user with an unprivileged user. see https://docs.ansible.com/ansible/latest/user_guide/become.html#id6
       ansible_ssh_pipelining: yes
   - name: Install tutorial HTML converter
     copy:
       src: tutorial-to-html.sh
       dest: /usr/local/bin/
       mode: '0755'
   - name: Run tutorial HTML converter
     command: /usr/local/bin/tutorial-to-html.sh
   - name: Install tutorial updater
     copy:
       src: tutorial-update.sh
       dest: /usr/local/bin/
       mode: '0755'
   # MAIL
   - name: Install mailname
     copy:
       content: 'malaga'
       dest: /etc/mailname
   - name: Install postfix catchall
     copy:
       content: '/.*/'
       dest: /etc/postfix/catchall
   - name: Install postfix main.cf
     copy:
       src: main.cf
       dest: /etc/postfix/
   - name: reload postfix
     systemd:
       name: postfix
       state: reloaded
   - name: Set mail_location in dovecot configuration
     lineinfile:
       path: /etc/dovecot/conf.d/10-mail.conf
       regexp: "^mail_location = "
       line: "mail_location = maildir:~/Maildir"
   - name: configure roundcube
     lineinfile:
       path: /etc/roundcube/config.inc.php
       regexp: "^$config['default_host']"
       line: "$config['default_host'] = 'localhost';"
   - name: enable roundcube in apache
     lineinfile:
       path: /etc/apache2/conf-enabled/roundcube.conf
       line: "Alias /roundcube /var/lib/roundcube"
   # RESET
   - name: install reset script
     copy:
       src: reset-intelmq.sh
       dest: /usr/local/bin/
       mode: '0755'
